[versions]
compose = "1.11.1"
detekt = "2.0.0-alpha.6"
dbusJava = "5.2.0"
fileKit = "0.15.0"
humanReadable = "2.0.0-alpha02"
konture = "0.8.1"
kotlin = "2.4.10"
kotlinxSerialization = "1.11.0"
nucleus = "2.5.1"
slf4j = "2.0.18"
testBalloon = "1.0.1-K2.4.0"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
konture = { id = "io.github.baole.konture", version.ref = "konture" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nucleus = { id = "dev.nucleusframework", version.ref = "nucleus" }
powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
testBalloon = { id = "de.infix.testBalloon", version.ref = "testBalloon" }

[libraries]
dbusJava-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbusJava" }
detekt-rules-ktlint = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
fileKit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "fileKit" }
humanReadable = { module = "nl.jacobras:Human-Readable", version.ref = "humanReadable" }
konture = { module = "io.github.baole:konture", version.ref = "konture" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
nucleus-application = { module = "dev.nucleusframework:nucleus.nucleus-application", version.ref = "nucleus" }
nucleus-darkmode-detector = { module = "dev.nucleusframework:nucleus.darkmode-detector", version.ref = "nucleus" }
nucleus-decorated-window-tao = { module = "dev.nucleusframework:nucleus.decorated-window-tao", version.ref = "nucleus" }
nucleus-fsWatcher = { module = "dev.nucleusframework:nucleus.fs-watcher", version.ref = "nucleus" }
nucleus-notification-common = { module = "dev.nucleusframework:nucleus.notification-common", version.ref = "nucleus" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
testBalloon-framework-core = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testBalloon" }
